### PR TITLE
Fix for pagination with filter

### LINKED ISSUE #5: With filters on right now, adding a todo will bring up an invalid pagination bar.
This might be invalid if we implement pagination for filtering and sorting.

Steps to reproduce:
1. Filter for some tag (checking/unchecking any of the filter will do)
2. Add/delete a todo.
3. Observe the bottom of the page has a invalid pagination bar.

This part of the code is pretty fugly. So yeah.

### PR DESCRIPTION
**Pull request by travellingprog**
Filtered todo results are now paginated. Many parts of the Todos controller code have been changed so that many functions now point to `$scope.update()`. Also, the todos list is always provided with a call to `/filter`, never to the index route. The `$scope.update()` function can also be provided an optional message that will appears after a successful update. Finally, a Python unittest was added for the `/filter` route.

Fixes [issue 5](https://github.com/shuhaowu/projecto/issues/5)

### CODE REVIEW

**Comment by shuhaowu** [comment]
One corner case: if you have 21 todos and 20 of them have the tag "tag1" and the remaining one has the tag "tag2". If you go to page two and then uncheck the filter for tag1, it will show that there are no todos.

File: static/js/develop/controllers/todos.js [hunk 1]
```diff
@@ -204,18 +242,24 @@
...
               var i = $scope.editMode[todoKey]._index;
-              delete $scope.editMode[todoKey]._index;
-              $scope.todos[i] = data;
               delete $scope.editMode[todoKey];
+              if (noCurrentEdits()) {
+                $scope.update(msg);
+              }
+              else {
+                $scope.todos[i] = data;
+                $("body").statusmsg("open", msg, {type: "success", autoclose: 1000});
```
Comment (shuhaowu) [inline static/js/develop/controllers/todos.js]: This autoclose time out is really really fast on my machine (it seems.. at least) Mind if we change this to 2000? I think that's the standard everywhere else. Again, i'll rework that part (the status/toast message) ASAP.

File: static/js/develop/controllers/todos.js [hunk 2]
```diff
@@ -319,4 +330,8 @@
 
     }]
   );
-})();
\ No newline at end of file
+})();
+
+
+// NOTE: Clicking any filter box will close any Edit form currently open. I believe that this is acceptable
```
Comment (shuhaowu) [inline static/js/develop/controllers/todos.js]: Perhaps add to see if there are any changes and show a confirm dialog? If this is not too important now, we could file a bug and fix it later.

File: static/partials/todos.html [hunk 3]
```diff
@@ -57,17 +63,22 @@
       <p>Number of Todos: {[ totalTodos ]}</p>
     </div>
   </div>
+
+  <!-- Todo list -->
   <div class="large-9 columns">
     <div class="panel" ng-repeat="todo in todos">
+
+      <!-- SUGGESTION: Make a separate todoItem template + controller -->
```
Comment (shuhaowu) [inline static/partials/todos.html]: +2 

Especially since we need to do single todo view (with comments and whatnot)

Do you want to take this or do you want me to take this?

File: static/partials/todos.html [hunk 4]
```diff
@@ -77,13 +88,16 @@
       </form>
 
 
+      <!-- QUESTION: What dictates whether this <div> is created or not? Not obvious by looking at this
```
Comment (shuhaowu) [inline static/partials/todos.html]: It's always there and is hidden. It is expanded when you click. 

We should also probably remove this comment.

File: static/partials/todos.html [hunk 5]
```diff
@@ -121,22 +135,34 @@
       <p>No todo items. Hurray!</p>
     </div>
 
+
+    <!-- Pagination -->
```
Comment (shuhaowu) [inline static/partials/todos.html:134]: These comments probably need to be stripped. You can put them on the wiki if you want to.

File: static/partials/todos.html [hunk 6]
```diff
@@ -121,22 +135,34 @@
...
+      <li ng-repeat="i in pages" ng-class="{current: i == currentPage}"><a href="" ng-click="goToPage({[i]})">{[ i ]}</a></li>
     </ul>
 
+    
+
     <ul class="pagination right" ng-show="totalPages >= 9">
-      <li ng-class="{current: currentPage == 1}"><a href="#/projects/{[ currentProject.key ]}/todos/pages/1">1</a></li>
-      <li ng-class="{current: currentPage == 2}"><a href="#/projects/{[ currentProject.key ]}/todos/pages/2">2</a></li>
-      <li ng-show="currentPage == 2"><a href="#/projects/{[ currentProject.key ]}/todos/pages/{[ 3 ]}">3</a></li>
+      <li ng-class="{current: currentPage == 1}"><a href="" ng-click="goToPage(1)">1</a></li>
```
Comment (shuhaowu) [inline static/partials/todos.html:140]: I'm sorry for this mess :P 

Pagination is pretty hard... it must be said.

File: static/js/develop/controllers/todos.js (hunk 1 above)
Comment (travellingprog) [inline static/js/develop/controllers/todos.js]: sure

File: static/partials/todos.html (hunk 4 above)
Comment (travellingprog) [inline static/partials/todos.html]: kk

File: static/partials/todos.html (hunk 5 above)
Comment (travellingprog) [inline static/partials/todos.html:134]: If you're talking about the comments under pagination, I can remove those since I have all that info written in the corresponding info. I think I kept them there because I'm probably going to work on that soon anyways.

File: static/partials/todos.html (hunk 6 above)
Comment (travellingprog) [inline static/partials/todos.html:140]: lol no worries

File: static/partials/todos.html (hunk 3 above)
Comment (travellingprog) [inline static/partials/todos.html]: I can take this on, I'll make this a new issue if there isn't one yet for this. I put this comment as a reminder, want me to take it off?

Comment (shuhaowu) [inline static/partials/todos.html]: A new issue will be fine! Eventually this needs to be taken off as it will render out on the client.

File: static/partials/todos.html (hunk 5 above)
Comment (shuhaowu) [inline static/partials/todos.html:134]: Sure thing. Just when we merge try not to put too much comment in HTML as it gets sent over the wire too.

File: static/js/develop/controllers/todos.js (hunk 2 above)
Comment (travellingprog) [inline static/js/develop/controllers/todos.js]: K, I'll add that behavior

**Comment by travellingprog** [comment]
still need to make a change in `static/js/develop/controllers/todos.js`

**Comment by shuhaowu** [comment]
Take your time :D

**Comment by travellingprog** [comment]
k, should all be good now. Aside from the edits you mentioned, I've also made a change in `deleteTodo()` so that it checks if another todo is currently being edited or not. If so, the current Todo page is not redone. Instead, the todo that was deleted will be taken of the UI, and `$scope.totalTodos` is updated as well (so that the "Number of Todos" label is updated). 

For example, suppose we have 25 todos and you are viewing page 1. On this page, you only see the first 20 todos, which include _todoA_ and _todoB_. You click on the _Edit_ button of a _todoA_. Then you click on the _Delete_ button of _todoB_ and confirm deletion. That action will **not** close the Edit form of _todoA_, but it will make the current page display 19 todos instead of 20. However, when you save _todoA_ (and assuming no other todos are being edited), the page will be recomputed and display 20 todos again.

**Comment by shuhaowu** [comment]
:+1: with one little change to the confirm message

Looks good to me. Awesome work! :sailboat:

**Comment by travellingprog** [comment]
Changed the warning message

**Comment by shuhaowu** [comment]
:+1: I'll merge this for now (as I want to close a bunch of bugs!), but we should probably merge our own PR :P
